import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import {
  ClerkProvider
} from "@clerk/nextjs";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { ContextProvider } from "@/components/providers/context-provider";
import { ModalProvider } from "@/components/providers/modal-provider";



const open_Sans = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Team chat Application",
  description: "Generated by Team chat Application",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  

  return (
    <html lang="en" suppressHydrationWarning>
        <ClerkProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem={false}
            storageKey="discord-themes"
          >
            <ContextProvider>
              <ModalProvider/>
                <body className={cn(open_Sans.className, "bg-white dark:bg-[#313338]")}>
                  {/* <Header /> */}
                  {children}
                </body>
            </ContextProvider>
          </ThemeProvider>

        </ClerkProvider>

    </html>
  );
}
